name: "ci"
on: [push]
jobs:
  ci:
    name: "ci"
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: "deno fmt --check"
    - run: "deno lint"
    - run: "deno test -A --allow-none"
