name: ci

on: [push]

jobs:
  build:
    name: Format, Lint and Test
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'WIP:')"
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Tests
        run: deno test -A --allow-none
      
      - name: stuff
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          export LATEST_VERSION="$(deno run -A --no-check -q scripts/getLatestVersion.ts)"
          echo $LATEST_VERSION
