name: ci

on: [push]

jobs:
  build:
    name: Format, Lint and Test
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'WIP:')"
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Tests
        run: deno test -A --allow-none
      
      - name: Release
        if: "contains(github.event.head_commit.message, '#major') || contains(github.event.head_commit.message, '#minor') || contains(github.event.head_commit.message, '#patch') || contains(github.event.head_commit.message, '#pre')"
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY .repository
          cd .repository
          git checkout $GITHUB_REF
          SCRIPTS="https://raw.githubusercontent.com/ihack2712/workflow-testing/1241729ebfcc0e3d912382332b9b00d9b28d4db4/scripts"
          OLD_VERSION=$(deno run -A $SCRIPTS/version.ts)
          rm -rf version.ts && echo "export default \"$(deno run -A $SCRIPTS/update.ts "$(deno run -A $SCRIPTS/latest.ts)" "${{ github.event.head_commit.message }}")\";" >> version.ts
          NEW_VERSION=$(deno run -A $SCRIPTS/version.ts)
          echo $NEW_VERSION $OLD_VERSION
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Incremented version to '$NEW_VERSION'."
          git tag $NEW_VERSION
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git push -fu origin $NEW_VERSION
          
          deno compile -o dot-x86_64-pc-windows-msvc --target x86_64-pc-windows-msvc -A cli.ts
          deno compile -o dot-x86_64-unknown-linux-gnu --target x86_64-unknown-linux-gnu -A cli.ts
          deno compile -o dot-x86_64-apple-darwin --target x86_64-apple-darwin -A cli.ts
          
          zip dot-x86_64-pc-windows-msvc.zip dot-x86_64-pc-windows-msvc
          zip dot-x86_64-unknown-linux-gnu.zip dot-x86_64-unknown-linux-gnu
          zip dot-x86_64-apple-darwin.zip dot-x86_64-apple-darwin
          
      
      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        if: "contains(github.event.head_commit.message, '#major') || contains(github.event.head_commit.message, '#minor') || contains(github.event.head_commit.message, '#patch') || contains(github.event.head_commit.message, '#pre')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dot-x86_64-pc-windows-msvc.zip
            dot-x86_64-unknown-linux-gnu.zip
            dot-x86_64-apple-darwin.zip
          draft: true
